jobs:
  build:
    machine: true
    working_directory: ~/isle
    shell: /bin/bash --login
    steps:
      - checkout
      # sed/replace some release number into feature branches in sample d-c (from this repo, with build instrs not remote images)
      # git clone main ISLE repo
      # replace D-C in main ISLE repo with the modified one above
      # switch to test env by overwriting the .env
      # git clone ISLE tomcat image as it needs to be built first as a base image https://github.com/Born-Digital-US/isle-tomcat
      # ^ is this an additional docker-compose or dockerfile?
      # docker-compose -f tomcat_build.yaml build docker-compose up -d
      - run: ls
  test:
    machine: true
    working_directory: ~/isle
    shell: /bin/bash --login
    steps:
      - checkout
      - run: ls
  deploy:
    machine: true
    working_directory: ~/isle
    shell: /bin/bash --login
    steps:
      - checkout
      - run: ls
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
