version: 2.1

jobs:
  build:
    machine: true
    working_directory: ~/build
    shell: /bin/bash --login
    steps:
      - checkout
      - run:
          name: Clone latest ISLE & create the data directory
          command: |
            git clone -b ISLE-v.1.5-dev https://github.com/Born-Digital-US/ISLE.git ISLE
            mkdir ~/build/ISLE/data
      - run:
          name: Fetch behat suite repo
          command: |
            cd ~/build
            git clone https://github.com/Islandora-Collaboration-Group/isle-behat.git isle-behat
      - run:
          name: Switch to using TEST profile for docker-compose
          command: |
            cd ~/build
            mv .env ~/build/ISLE/.env
            mv docker-compose.test.yml ~/build/ISLE/docker-compose.test.yml
            mv tomcat_build.yml ~/build/ISLE/tomcat_build.yml
      - run:
          name: Get docker-compose 1.25.5
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      # First build the tomcat image then startup all containers like usual
      - run: cd ~/build/ISLE && docker-compose -f tomcat_build.yml build
      - run: cd ~/build/ISLE && docker-compose up -d
      - run: sleep 40
      - run:
          name: Start the Drupal installation script
          command: |
            set -x
            docker ps -a
            docker exec -it isle-apache-td bash -c "cd / && ls -lha && cd /utility-scripts/ && ls -lha"
            docker exec -it isle-apache-td bash /utility-scripts/isle_drupal_build_tools/isle_islandora_installer.sh                                           
          no_output_timeout: 20m
      - run:
          name: Drush en basic dependencies
          command: |
            docker exec -it isle-apache-td bash -c "cd /var/www/html/sites/all/modules/islandora && git clone https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories.git"
            docker exec -it isle-apache-td bash -c "cd /var/www/html && drush -y -u 1 en islandora_oralhistories"
            docker exec -it isle-apache-td bash -c "cd /var/www/html && drush dis overlay -y"
            sudo -- sh -c "echo 127.0.0.1 isle.localdomain >> /etc/hosts"
          no_output_timeout: 20m
      - run:
          name: Set up Varnish
          command: |
            docker cp ~/build/ISLE/scripts/varnish/isle_varnish_drupal_module_installer.sh isle-apache-td:/var/www/html/isle_varnish_drupal_module_installer.sh
            docker exec -it isle-apache-td bash -c "cd /var/www/html/ && chmod +x isle_varnish_drupal_module_installer.sh"
            docker exec -it isle-apache-td bash -c "cd /var/www/html && ./isle_varnish_drupal_module_installer.sh"
          no_output_timeout: 10m
      - run:
          # While we don't need these if we're not doing bulk ingest, sometimes they are dependencies for batch functions
          name: Drush en batch dependencies
          command: |
            docker exec -it isle-apache-td bash -c "cd /var/www/html && drush -y -u 1 en islandora_batch"
            docker exec -it isle-apache-td bash -c "cd /var/www/html/sites/all/modules/islandora && git clone https://github.com/mjordan/islandora_batch_with_derivs.git"
            docker exec -it isle-apache-td bash -c "cd /var/www/html && drush -y -u 1 en islandora_batch_with_derivs"
            docker exec -it isle-apache-td bash -c "cd /var/www/html && drush -y -u 1 en islandora_book_batch"
            docker exec -it isle-apache-td bash -c "cd /var/www/html && drush -y -u 1 en islandora_newspaper_batch"
            docker exec -it isle-apache-td bash -c "cd /var/www/html/sites/all/modules/islandora && git clone https://github.com/MarcusBarnes/islandora_compound_batch.git"
            docker exec -it isle-apache-td bash -c "cd /var/www/html && drush -y -u 1 en islandora_compound_batch"
          no_output_timeout: 20m

      - run:
          name: Set up for BEHAT on remote server
          command: |
            docker cp ~/build/ISLE/isle-behat isle-apache-td:/var/www/html/sites/behat
            docker exec -it isle-apache-td bash -c "chown -R islandora:www-data /var/www/html/sites/behat/"
            docker exec -it isle-apache-td bash -c "cd /var/www/html/sites/behat && composer install "
            docker exec -it isle-apache-td bash -c "chmod 700 /var/www/html/sites/behat/run-isle-tests.sh"
            sudo chmod -R 777 ~/build/ISLE/data/apache/html/sites/behat/debug
      - run:
          name: Run the behat tests
          command: |
            docker exec -it isle-apache-td bash -c "cd /var/www/html/sites/behat && ./run-isle-tests.sh --run=services"
            docker exec -it isle-apache-td bash -c "cd /var/www/html/sites/behat && ./run-isle-tests.sh --run=apache"
          no_output_timeout: 20m

      - run:
          name: Fix artifact file permissions
          command: |
            sudo mkdir /home/circleci/artifacts
            sudo cp -r /home/circleci/ISLE/data/apache/html/sites/behat/debug/ /home/circleci/artifacts
            sudo chown -R circleci:circleci /home/circleci/artifacts/
          when: always
      - store_artifacts:
          path: /home/circleci/artifacts/
          destination: behat-artifacts

  test:
    machine: true
    working_directory: ~/build
    shell: /bin/bash --login
    steps:
      - checkout
      - run: ls
  deploy:
    machine: true
    working_directory: ~/build
    shell: /bin/bash --login
    steps:
      - checkout
      - run: ls
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
